baseurl = "/"
languageCode = "en-us"
title = "Kaziaa Blog"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/Kaziaa/Blog.git"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/KaziaaAlam"
[[menu.main]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/kazi-alam-phd-9b16b1113/"
[[menu.main]]
    name = "Publication"
    url = "https://scholar.google.no/citations?user=BOBvDrwAAAAJ&hl=en"
[[menu.main]]
    name = "Blog"
    url = ""

    
[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "kazi.png"
    width = 50
    height = 50
    alt = "Logo"

